# Generated by Django 2.2.4 on 2019-12-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contactNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('gstin', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=200)),
                ('contactNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Merchant')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Seller')),
            ],
        ),
    ]
