# Generated by Django 2.2.9 on 2019-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='bussiness_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
